image: archlinux
packages:
  - make
  - mktiupgrade
  - genkfs
  - mkrom
  - patchrom
sources:
  - https://github.com/KnightOS/kernel
  - https://github.com/KnightOS/scas
environment:
  project: kernel
tasks:
  - scas: |
      cd scas
      mkdir build
      cd build
      cmake ..
      make
      sudo make install
  - ti73: |
      cd ${project}
      make TI73
  - ti83p: |
      cd ${project}
      make clean
      make TI83p
  - ti83pse: |
      cd ${project}
      make clean
      make TI83pSE
  - ti84p: |
      cd ${project}
      make clean
      make TI84p
  - ti84pse: |
      cd ${project}
      make clean
      make TI84pSE
  - ti84pcse: |
      cd ${project}
      make clean
      make TI84pCSE
